CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Services" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(1000),
    "DurationMinutes" integer NOT NULL,
    "Price" numeric(12,2) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Services_DurationMinutes_Positive" CHECK ("DurationMinutes" > 0),
    CONSTRAINT "CK_Services_Price_NonNegative" CHECK ("Price" >= 0)
);

CREATE TABLE "Staffs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Staffs" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "Role" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Role" CHECK ("Role" IN ('Customer', 'Admin'))
);

CREATE TABLE "WorkSchedules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StaffId" bigint NOT NULL,
    "WorkDate" date NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "EndTime" time without time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_WorkSchedules_StartBeforeEnd" CHECK ("StartTime" < "EndTime"),
    CONSTRAINT "FK_WorkSchedules_Staffs_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Staffs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Bookings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "BookingCode" character varying(50) NOT NULL,
    "CustomerId" bigint NOT NULL,
    "ServiceId" bigint NOT NULL,
    "StaffId" bigint NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CustomerNote" character varying(1000),
    "CancellationReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Bookings_StartBeforeEnd" CHECK ("StartTime" < "EndTime"),
    CONSTRAINT "CK_Bookings_Status" CHECK ("Status" IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
    CONSTRAINT "FK_Bookings_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Bookings_Staffs_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Staffs" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Bookings_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Bookings_CustomerId_CreatedAt" ON "Bookings" ("CustomerId", "CreatedAt");

CREATE INDEX "IX_Bookings_ServiceId" ON "Bookings" ("ServiceId");

CREATE INDEX "IX_Bookings_StaffId_StartTime_EndTime_Status" ON "Bookings" ("StaffId", "StartTime", "EndTime", "Status");

CREATE INDEX "IX_Bookings_Status_CreatedAt" ON "Bookings" ("Status", "CreatedAt");

CREATE UNIQUE INDEX "UX_Bookings_BookingCode" ON "Bookings" ("BookingCode");

CREATE INDEX "IX_Services_IsActive_Name" ON "Services" ("IsActive", "Name");

CREATE UNIQUE INDEX "UX_Staffs_Email" ON "Staffs" ("Email");

CREATE UNIQUE INDEX "UX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_WorkSchedules_StaffId_WorkDate" ON "WorkSchedules" ("StaffId", "WorkDate");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260927132204_InitialCreate', '8.0.11');

COMMIT;

